version: "3.9"

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
      args:
        - version=${PHP_VERSION}
    volumes:
      - "./src:/var/www/html"
    ports:
      - "${FE_PORT}:80"
    restart: on-failure
